### PR TITLE
[fix] skip expiration for keygen related proposals

### LINKED ISSUE #609: [TASK] ProposalSetUpdate and RefreshVote proposals should never expire
**Task summary**
Currently all proposals have an expiry limit, but it would be better if we can assign that depending on the type of proposal, certain types namely `ProposalSetUpdate` and `RefreshVote` is necessary for keygen process to complete and session to rotate, these should never expire and should be signed.

### PR DESCRIPTION
**Pull request by 1xstj**
**Summary of changes**
Changes introduced in this pull request:
- skip expiration for keygen related proposals

**Reference issue to close (if applicable)**
Closes #609

### CODE REVIEW

**Review by shekohex — COMMENTED** [review]
Makes sense. But we also should not add more as long as we already have one queued, right?

**Comment by tbraun96** [comment]
> Makes sense. But we also should not add more as long as we already have one queued, right?

Yes, this would make sense.

**Comment by 1xstj** [comment]
> Makes sense. But we also should not add more as long as we already have one queued, right?

Yes this will never happen though, so we run keygen the NextDkgKey is added to chain then a RefreshProposal is created. So lets say this is never signed, a new keygen will not run since the NextDKGKey is already onchain. This is what leads to us stalling since the RefreshProposal expired without signature and a new keygen wont execute.

**Comment by shekohex** [comment]
> > Makes sense. But we also should not add more as long as we already have one queued, right?
> 
> Yes this will never happen though, so we run keygen the NextDkgKey is added to chain then a RefreshProposal is created. So lets say this is never signed, a new keygen will not run since the NextDKGKey is already onchain. This is what leads to us stalling since the RefreshProposal expired without signature and a new keygen wont execute.

Did not have a Auto Trigger or something like that which runs every `N = 10` blocks and see if we have a Next Public Key and that we do not have a Refresh Proposal and in that case it inserts a new one? If we still have that logic still, I would say we should remove it, as it is not useful now (after this PR)

**Comment by 1xstj** [comment]
> > > Makes sense. But we also should not add more as long as we already have one queued, right?
> > 
> > 
> > Yes this will never happen though, so we run keygen the NextDkgKey is added to chain then a RefreshProposal is created. So lets say this is never signed, a new keygen will not run since the NextDKGKey is already onchain. This is what leads to us stalling since the RefreshProposal expired without signature and a new keygen wont execute.
> 
> Did not have a Auto Trigger or something like that which runs every `N = 10` blocks and see if we have a Next Public Key and that we do not have a Refresh Proposal and in that case it inserts a new one? If we still have that logic still, I would say we should remove it, as it is not useful now (after this PR)

These are two different cases
1. Keygen fails : In that case, the auto trigger will tell the dkg-gadget to run the keygen process again after 10 blocks
2. Keygen suceeds and signing fails : In this case also the auto trigger will tell the dkg-gadget to run the keygen process again but the gadget sees that the NextDKGKey is already onchain so skips it

This is addressing point2

**Review by shekohex — APPROVED** [review]
LG!

**Pull request merged**
